//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class childrenDetail
    {
        public int Id { get; set; }
        public Nullable<int> MembershipIDNo { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNo { get; set; }
        public string EmailAddress { get; set; }
        public string WorkSch { get; set; }
        public string Fullname { get; set; }
        public Nullable<int> GenderID { get; set; }
    
        public virtual MemebershipT MemebershipT { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
