//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartList
    {
        public int Id { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> DeptId { get; set; }
    
        public virtual Departmental Departmental { get; set; }
        public virtual MemebershipT MemebershipT { get; set; }
    }
}
