//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaithBillLog
    {
        public int Id { get; set; }
        public int BillRef { get; set; }
        public string BillItemType { get; set; }
        public string BillPaymentType { get; set; }
        public string BillUID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<decimal> PaidInAmt { get; set; }
        public Nullable<decimal> PaidOutAmt { get; set; }
        public decimal TotalAmt { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<bool> CancellationStatus { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
