//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithAG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hpsadmin_dfaithagEntities : DbContext
    {
        public hpsadmin_dfaithagEntities()
            : base("name=hpsadmin_dfaithagEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<childrenDetail> childrenDetails { get; set; }
        public virtual DbSet<DepartList> DepartLists { get; set; }
        public virtual DbSet<Departmental> Departmentals { get; set; }
        public virtual DbSet<MaritalStatu> MaritalStatus { get; set; }
        public virtual DbSet<MemebershipT> MemebershipTs { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<MemberTitle> MemberTitles { get; set; }
        public virtual DbSet<TbIdentification> TbIdentifications { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<TithePayment> TithePayments { get; set; }
        public virtual DbSet<FaithBillLog> FaithBillLogs { get; set; }
    }
}
