//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaithAG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemebershipT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemebershipT()
        {
            this.childrenDetails = new HashSet<childrenDetail>();
            this.DepartLists = new HashSet<DepartList>();
            this.TithePayments = new HashSet<TithePayment>();
        }
    
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string PhoneNo { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public string ResidentialAddress { get; set; }
        public string Address { get; set; }
        public Nullable<int> MaritalStatusID { get; set; }
        public string WorkPlace { get; set; }
        public string UID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Fullname { get; set; }
        public string City { get; set; }
        public string HomeTown { get; set; }
        public Nullable<int> SpouseId { get; set; }
        public string SpouseFullname { get; set; }
        public string Profession { get; set; }
        public Nullable<int> GenderIDn { get; set; }
        public string Profile_Img { get; set; }
        public Nullable<int> MemTitleID { get; set; }
        public string NextofKin { get; set; }
        public string KinContact { get; set; }
        public string DigitalAddress { get; set; }
        public Nullable<int> IDType { get; set; }
        public string IDNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<childrenDetail> childrenDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartList> DepartLists { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MemberTitle MemberTitle { get; set; }
        public virtual TbIdentification TbIdentification { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TithePayment> TithePayments { get; set; }
    }
}
